"""
Import time entries from PDF format - Optimized for HWI Ponto PDFs
"""
import pdfplumber
import re
from datetime import datetime
import logging

def parse_pdf_timesheet(file_path):
    """
    Parse PDF timesheet generated by HWI Ponto application.
    
    PDF Structure (REGISTO DIÁRIO DETALHADO table):
    | Data | Dia | Entradas/Saídas | Total | Trab.Supl. | Observações | Pagamento |
    
    Returns: dict with structure:
    {
        'success': bool,
        'entries': [
            {
                'date': 'YYYY-MM-DD',
                'time_entries': [{'start_time': 'HH:MM', 'end_time': 'HH:MM'}, ...],
                'outside_residence_zone': bool,
                'location_description': str or None,
                'observations': str or None,
                'status': str  # TRABALHADO, FOLGA, FERIADO, FÉRIAS, FALTA
            }
        ],
        'metadata': {
            'collaborator': str,
            'period_start': str,
            'period_end': str
        }
    }
    """
    try:
        entries_list = []
        metadata = {
            'collaborator': None,
            'period_start': None,
            'period_end': None
        }
        
        # Try to detect year from period text
        detected_year = None
        
        with pdfplumber.open(file_path) as pdf:
            logging.info(f"📄 Parsing PDF with {len(pdf.pages)} pages")
            
            for page_num, page in enumerate(pdf.pages):
                # Extract text for metadata
                text = page.extract_text() or ""
                
                logging.info(f"📃 Processing page {page_num + 1}")
                
                # Extract metadata from first page
                if page_num == 0:
                    # Extract collaborator name
                    collab_match = re.search(r'Colaborador:\s*(.+?)(?:\n|$)', text)
                    if collab_match:
                        metadata['collaborator'] = collab_match.group(1).strip()
                        logging.info(f"  👤 Collaborator: {metadata['collaborator']}")
                    
                    # Extract period (format: DD/MM/YYYY - DD/MM/YYYY)
                    period_match = re.search(r'Período:\s*(\d{1,2}/\d{1,2}/\d{4})\s*[-–]\s*(\d{1,2}/\d{1,2}/\d{4})', text)
                    if period_match:
                        start_str, end_str = period_match.groups()
                        try:
                            start_dt = datetime.strptime(start_str, '%d/%m/%Y')
                            end_dt = datetime.strptime(end_str, '%d/%m/%Y')
                            metadata['period_start'] = start_dt.strftime('%Y-%m-%d')
                            metadata['period_end'] = end_dt.strftime('%Y-%m-%d')
                            detected_year = end_dt.year
                            logging.info(f"  📅 Period: {start_str} - {end_str}")
                        except ValueError:
                            pass
                
                # Extract tables
                tables = page.extract_tables()
                
                if not tables:
                    logging.info(f"  ⚠️ No tables found on page {page_num + 1}")
                    continue
                
                for table_idx, table in enumerate(tables):
                    if not table or len(table) < 2:
                        continue
                    
                    # Find header row - look for "Data" and "Dia" columns
                    header_idx = None
                    col_indices = {}
                    
                    for idx, row in enumerate(table):
                        if not row:
                            continue
                        
                        row_text = ' '.join([str(cell or '').strip() for cell in row])
                        
                        # Check if this is the header row
                        if 'Data' in row_text and 'Dia' in row_text:
                            header_idx = idx
                            
                            # Map column indices
                            for col_idx, cell in enumerate(row):
                                cell_text = str(cell or '').strip().lower()
                                if 'data' in cell_text and 'dia' not in cell_text:
                                    col_indices['data'] = col_idx
                                elif cell_text == 'dia':
                                    col_indices['dia'] = col_idx
                                elif 'entrada' in cell_text or 'saída' in cell_text:
                                    col_indices['entries'] = col_idx
                                elif 'total' in cell_text and 'trab' not in cell_text:
                                    col_indices['total'] = col_idx
                                elif 'trab' in cell_text and 'supl' in cell_text:
                                    col_indices['overtime'] = col_idx
                                elif 'observa' in cell_text:
                                    col_indices['observations'] = col_idx
                                elif 'pagamento' in cell_text:
                                    col_indices['payment'] = col_idx
                            
                            logging.info(f"  📊 Found header at row {idx}: {col_indices}")
                            break
                    
                    if header_idx is None:
                        continue
                    
                    # Set default column indices if not found
                    if 'data' not in col_indices:
                        col_indices['data'] = 0
                    if 'dia' not in col_indices:
                        col_indices['dia'] = 1
                    if 'entries' not in col_indices:
                        col_indices['entries'] = 2
                    if 'total' not in col_indices:
                        col_indices['total'] = 3
                    if 'overtime' not in col_indices:
                        col_indices['overtime'] = 4
                    if 'observations' not in col_indices:
                        col_indices['observations'] = 5
                    if 'payment' not in col_indices:
                        col_indices['payment'] = 6
                    
                    # Process data rows
                    for row_idx in range(header_idx + 1, len(table)):
                        row = table[row_idx]
                        if not row or len(row) < 3:
                            continue
                        
                        try:
                            # Get date
                            date_cell = str(row[col_indices['data']] or '').strip()
                            
                            # Match date format DD/MM
                            date_match = re.search(r'(\d{1,2})/(\d{1,2})', date_cell)
                            if not date_match:
                                continue
                            
                            day, month = map(int, date_match.groups())
                            
                            # Determine year
                            if detected_year:
                                year = detected_year
                                # Handle year boundary (e.g., period Nov-Dec might have entries in both years)
                                if metadata['period_start']:
                                    period_start_month = int(metadata['period_start'].split('-')[1])
                                    # If entry month is less than period start month and period spans year boundary
                                    if month < period_start_month and period_start_month > 6:
                                        year = detected_year + 1
                            else:
                                year = datetime.now().year
                            
                            date_str = f"{year}-{month:02d}-{day:02d}"
                            
                            # Get entries column
                            entries_cell = str(row[col_indices['entries']] or '').strip()
                            
                            # Detect status from entries column
                            status = 'TRABALHADO'
                            entries_upper = entries_cell.upper()
                            
                            if 'FOLGA' in entries_upper:
                                status = 'FOLGA'
                            elif 'FERIADO' in entries_upper:
                                status = 'FERIADO'
                            elif 'FÉRIAS' in entries_upper or 'FERIAS' in entries_upper:
                                status = 'FÉRIAS'
                            elif 'FALTA' in entries_upper:
                                status = 'FALTA'
                            elif 'NÃO TRABALHADO' in entries_upper or 'NAO TRABALHADO' in entries_upper:
                                status = 'NÃO TRABALHADO'
                            
                            # Get observations
                            observations = None
                            if col_indices.get('observations') and col_indices['observations'] < len(row):
                                obs_cell = str(row[col_indices['observations']] or '').strip()
                                if obs_cell and obs_cell != '-':
                                    observations = obs_cell
                            
                            # Get payment info (for outside_residence_zone)
                            outside_residence_zone = False
                            location_description = None
                            
                            if col_indices.get('payment') and col_indices['payment'] < len(row):
                                payment_cell = str(row[col_indices['payment']] or '').strip()
                                payment_upper = payment_cell.upper()
                                
                                if 'AJUDA DE CUSTO' in payment_upper or 'AJUDA DE CUSTAS' in payment_upper:
                                    outside_residence_zone = True
                                    # Extract location from parentheses
                                    loc_match = re.search(r'\(([^)]+)\)', payment_cell)
                                    if loc_match:
                                        location_description = loc_match.group(1).strip()
                                    else:
                                        # Try to extract from line after "Ajuda de Custos"
                                        lines = payment_cell.split('\n')
                                        for line in lines:
                                            if 'ajuda' not in line.lower() and '€' not in line and line.strip():
                                                location_description = line.strip()
                                                break
                            
                            # Parse time entries if status is TRABALHADO
                            time_pairs = []
                            
                            if status == 'TRABALHADO':
                                # Find all HH:MM-HH:MM patterns
                                # Handle various formats:
                                # - "09:00-13:00"
                                # - "09:00 - 13:00"
                                # - "9:00-13:00"
                                # - Multiple entries separated by newlines
                                
                                pair_matches = re.findall(
                                    r'(\d{1,2}:\d{2})\s*[-–]\s*(\d{1,2}:\d{2})',
                                    entries_cell
                                )
                                
                                for start_time, end_time in pair_matches:
                                    start_h, start_m = map(int, start_time.split(':'))
                                    end_h, end_m = map(int, end_time.split(':'))
                                    
                                    start_formatted = f"{start_h:02d}:{start_m:02d}"
                                    end_formatted = f"{end_h:02d}:{end_m:02d}"
                                    
                                    # Validate end > start (for same-day entries)
                                    if (end_h * 60 + end_m) > (start_h * 60 + start_m):
                                        time_pairs.append({
                                            'start_time': start_formatted,
                                            'end_time': end_formatted
                                        })
                                
                                # If no pairs found, try individual times
                                if not time_pairs:
                                    times = re.findall(r'(\d{1,2}:\d{2})', entries_cell)
                                    for i in range(0, len(times) - 1, 2):
                                        start_h, start_m = map(int, times[i].split(':'))
                                        end_h, end_m = map(int, times[i+1].split(':'))
                                        
                                        start_formatted = f"{start_h:02d}:{start_m:02d}"
                                        end_formatted = f"{end_h:02d}:{end_m:02d}"
                                        
                                        if (end_h * 60 + end_m) > (start_h * 60 + start_m):
                                            time_pairs.append({
                                                'start_time': start_formatted,
                                                'end_time': end_formatted
                                            })
                            
                            # Create entry
                            entry = {
                                'date': date_str,
                                'status': status,
                                'time_entries': time_pairs,
                                'outside_residence_zone': outside_residence_zone,
                                'location_description': location_description,
                                'observations': observations
                            }
                            
                            entries_list.append(entry)
                            
                            if time_pairs:
                                logging.info(f"  ✅ {date_str} ({status}): {len(time_pairs)} entries, outside_zone={outside_residence_zone}")
                            else:
                                logging.info(f"  📋 {date_str}: {status}")
                            
                        except Exception as e:
                            logging.warning(f"  ⚠️ Error processing row {row_idx}: {str(e)}")
                            continue
        
        # Sort entries by date
        entries_list.sort(key=lambda x: x['date'])
        
        # Count statistics
        worked_days = sum(1 for e in entries_list if e['status'] == 'TRABALHADO' and e['time_entries'])
        total_entries = sum(len(e['time_entries']) for e in entries_list)
        
        logging.info(f"📊 PDF Parse Complete:")
        logging.info(f"   Total days: {len(entries_list)}")
        logging.info(f"   Worked days: {worked_days}")
        logging.info(f"   Total time entries: {total_entries}")
        
        return {
            'success': True,
            'entries': entries_list,
            'total_days': len(entries_list),
            'worked_days': worked_days,
            'total_entries': total_entries,
            'metadata': metadata
        }
        
    except Exception as e:
        logging.error(f"❌ Error parsing PDF file: {str(e)}")
        import traceback
        logging.error(traceback.format_exc())
        return {
            'success': False,
            'error': str(e),
            'entries': []
        }
