"""
Import time entries from PDF format - Optimized for HWI Ponto PDFs
"""
import pdfplumber
import re
from datetime import datetime
import logging

def parse_pdf_timesheet(file_path):
    """
    Parse PDF timesheet generated by HWI Ponto application.
    
    PDF Structure (REGISTO DIÁRIO DETALHADO table):
    | Data | Dia | Entradas/Saídas | Total | Trab.Supl. | Observações | Pagamento |
    
    Handles:
    - Multiple entries per day (separated by \n)
    - Entries crossing midnight (00:00-XX:XX continuation)
    - Various status formats: nn FOLGA, n FERIADO, (n FÉRIAS
    - Ajuda de Custos with location in parentheses
    
    Returns: dict with structure:
    {
        'success': bool,
        'entries': [
            {
                'date': 'YYYY-MM-DD',
                'time_entries': [{'start_time': 'HH:MM', 'end_time': 'HH:MM'}, ...],
                'outside_residence_zone': bool,
                'location_description': str or None,
                'observations': str or None,
                'status': str  # TRABALHADO, FOLGA, FERIADO, FÉRIAS, FALTA
            }
        ],
        'metadata': {...}
    }
    """
    try:
        entries_list = []
        metadata = {
            'collaborator': None,
            'period_start': None,
            'period_end': None
        }
        
        # Try to detect year from period text
        detected_year = None
        
        with pdfplumber.open(file_path) as pdf:
            logging.info(f"📄 Parsing PDF with {len(pdf.pages)} pages")
            
            for page_num, page in enumerate(pdf.pages):
                # Extract text for metadata
                text = page.extract_text() or ""
                
                logging.info(f"📃 Processing page {page_num + 1}")
                
                # Extract metadata from first page
                if page_num == 0:
                    # Extract collaborator name
                    collab_match = re.search(r'Colaborador:\s*(.+?)(?:\n|$)', text)
                    if collab_match:
                        metadata['collaborator'] = collab_match.group(1).strip()
                        logging.info(f"  👤 Collaborator: {metadata['collaborator']}")
                    
                    # Extract period (format: DD/MM/YYYY - DD/MM/YYYY)
                    period_match = re.search(r'Período:\s*(\d{1,2}/\d{1,2}/\d{4})\s*[-–]\s*(\d{1,2}/\d{1,2}/\d{4})', text)
                    if period_match:
                        start_str, end_str = period_match.groups()
                        try:
                            start_dt = datetime.strptime(start_str, '%d/%m/%Y')
                            end_dt = datetime.strptime(end_str, '%d/%m/%Y')
                            metadata['period_start'] = start_dt.strftime('%Y-%m-%d')
                            metadata['period_end'] = end_dt.strftime('%Y-%m-%d')
                            detected_year = end_dt.year
                            logging.info(f"  📅 Period: {start_str} - {end_str}")
                        except ValueError:
                            pass
                
                # Extract tables
                tables = page.extract_tables()
                
                if not tables:
                    logging.info(f"  ⚠️ No tables found on page {page_num + 1}")
                    continue
                
                for table_idx, table in enumerate(tables):
                    if not table or len(table) < 2:
                        continue
                    
                    # Check if this is the daily records table
                    # Look for "Data" in first row/column
                    is_daily_table = False
                    header_idx = None
                    
                    for idx, row in enumerate(table):
                        if not row:
                            continue
                        row_text = ' '.join([str(cell or '').strip() for cell in row])
                        
                        # Check for header with "Data" and "Dia"
                        if 'Data' in row_text and 'Dia' in row_text:
                            is_daily_table = True
                            header_idx = idx
                            break
                        
                        # Also check if first cell is a date (DD/MM format)
                        first_cell = str(row[0] or '').strip()
                        if re.match(r'^\d{1,2}/\d{1,2}$', first_cell):
                            is_daily_table = True
                            header_idx = -1  # No header, data starts at 0
                            break
                    
                    if not is_daily_table:
                        continue
                    
                    logging.info(f"  📊 Found daily table {table_idx} (header at row {header_idx})")
                    
                    # Process data rows
                    start_row = header_idx + 1 if header_idx >= 0 else 0
                    
                    for row_idx in range(start_row, len(table)):
                        row = table[row_idx]
                        if not row or len(row) < 3:
                            continue
                        
                        try:
                            # Get date from first column
                            date_cell = str(row[0] or '').strip()
                            
                            # Match date format DD/MM
                            date_match = re.search(r'(\d{1,2})/(\d{1,2})', date_cell)
                            if not date_match:
                                continue
                            
                            day, month = map(int, date_match.groups())
                            
                            # Determine year based on period
                            year = detected_year or datetime.now().year
                            if metadata.get('period_start'):
                                period_start_month = int(metadata['period_start'].split('-')[1])
                                period_start_year = int(metadata['period_start'].split('-')[0])
                                # Handle year boundary
                                if month < period_start_month:
                                    year = period_start_year + 1
                                else:
                                    year = period_start_year
                            
                            date_str = f"{year}-{month:02d}-{day:02d}"
                            
                            # Get entries column (index 2)
                            entries_cell = str(row[2] or '').strip() if len(row) > 2 else ''
                            
                            # Detect status from entries column
                            status = 'TRABALHADO'
                            entries_upper = entries_cell.upper()
                            
                            # Check for various status formats
                            if 'FOLGA' in entries_upper:
                                status = 'FOLGA'
                            elif 'FERIADO' in entries_upper:
                                status = 'FERIADO'
                            elif 'FÉRIAS' in entries_upper or 'FERIAS' in entries_upper:
                                status = 'FÉRIAS'
                            elif 'FALTA' in entries_upper:
                                status = 'FALTA'
                            elif entries_cell == '-' or not entries_cell:
                                status = 'NÃO TRABALHADO'
                            
                            # Get observations (index 5)
                            observations = None
                            if len(row) > 5:
                                obs_cell = str(row[5] or '').strip()
                                if obs_cell and obs_cell != '-':
                                    observations = obs_cell
                            
                            # Get payment info (index 6)
                            outside_residence_zone = False
                            location_description = None
                            
                            if len(row) > 6:
                                payment_cell = str(row[6] or '').strip()
                                payment_upper = payment_cell.upper()
                                
                                if 'AJUDA DE CUSTO' in payment_upper or 'AJUDA DE CUSTAS' in payment_upper:
                                    outside_residence_zone = True
                                    # Extract location from parentheses
                                    loc_match = re.search(r'\(([^)]+)\)', payment_cell)
                                    if loc_match:
                                        location_description = loc_match.group(1).strip()
                            
                            # Parse time entries if status is TRABALHADO
                            time_pairs = []
                            
                            if status == 'TRABALHADO' and entries_cell:
                                # Split by newlines to handle multiple entries
                                entry_lines = entries_cell.replace('\n', ' ').strip()
                                
                                # Find all HH:MM-HH:MM patterns
                                # Handle formats: 09:00-13:00, 9:00-13:00, 08:55-00:00
                                pair_matches = re.findall(
                                    r'(\d{1,2}:\d{2})\s*[-–]\s*(\d{1,2}:\d{2})',
                                    entry_lines
                                )
                                
                                for start_time, end_time in pair_matches:
                                    start_h, start_m = map(int, start_time.split(':'))
                                    end_h, end_m = map(int, end_time.split(':'))
                                    
                                    start_formatted = f"{start_h:02d}:{start_m:02d}"
                                    end_formatted = f"{end_h:02d}:{end_m:02d}"
                                    
                                    # Handle midnight entries (00:00)
                                    # If end is 00:00, treat it as end of day (23:59)
                                    if end_h == 0 and end_m == 0:
                                        # This is an entry that goes until midnight
                                        # Keep it as-is for now, will be handled as 24:00
                                        end_formatted = "23:59"
                                    
                                    # Validate: end must be > start (unless it's midnight crossing)
                                    start_minutes = start_h * 60 + start_m
                                    end_minutes = end_h * 60 + end_m
                                    if end_h == 0 and end_m == 0:
                                        end_minutes = 24 * 60  # Treat as next day
                                    
                                    if end_minutes > start_minutes:
                                        time_pairs.append({
                                            'start_time': start_formatted,
                                            'end_time': end_formatted if end_formatted != "23:59" else "23:59"
                                        })
                                    elif start_h == 0 and start_minutes < 120:
                                        # This is a continuation from previous day (00:00-XX:XX)
                                        # Include it as a valid entry
                                        time_pairs.append({
                                            'start_time': start_formatted,
                                            'end_time': end_formatted
                                        })
                            
                            # Create entry
                            entry = {
                                'date': date_str,
                                'status': status,
                                'time_entries': time_pairs,
                                'outside_residence_zone': outside_residence_zone,
                                'location_description': location_description,
                                'observations': observations
                            }
                            
                            entries_list.append(entry)
                            
                            if time_pairs:
                                times_str = ', '.join([f"{t['start_time']}-{t['end_time']}" for t in time_pairs])
                                logging.info(f"  ✅ {date_str} ({status}): {times_str}")
                                if outside_residence_zone:
                                    logging.info(f"     📍 Fora zona: {location_description}")
                            else:
                                logging.info(f"  📋 {date_str}: {status}")
                            
                        except Exception as e:
                            logging.warning(f"  ⚠️ Error processing row {row_idx}: {str(e)}")
                            import traceback
                            logging.warning(traceback.format_exc())
                            continue
        
        # Sort entries by date
        entries_list.sort(key=lambda x: x['date'])
        
        # Count statistics
        worked_days = sum(1 for e in entries_list if e['status'] == 'TRABALHADO' and e['time_entries'])
        total_entries = sum(len(e['time_entries']) for e in entries_list)
        
        logging.info(f"📊 PDF Parse Complete:")
        logging.info(f"   Total days: {len(entries_list)}")
        logging.info(f"   Worked days: {worked_days}")
        logging.info(f"   Total time entries: {total_entries}")
        
        return {
            'success': True,
            'entries': entries_list,
            'total_days': len(entries_list),
            'worked_days': worked_days,
            'total_entries': total_entries,
            'metadata': metadata
        }
        
    except Exception as e:
        logging.error(f"❌ Error parsing PDF file: {str(e)}")
        import traceback
        logging.error(traceback.format_exc())
        return {
            'success': False,
            'error': str(e),
            'entries': []
        }
